---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove:
  - Safari
  - Mail
  - Photos
  - 'System Preferences'
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Maps
  - Music
  - Podcasts
  - News
  - 'Feedback Assistant'
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes

configure_sudoers: false
# sudoers_custom_config: ''
# sudoers_custom_config: |
#  %admin ALL=(ALL) NOPASSWD: ALL
 
mas_installed_apps:
 - { id: 1444383602 , name: "GoodNotes 5" }
 - { id: 360593530 , name: "Notability" }
 - { id: 1451685025 , name: "WireGuard" }
 - { id: 425424353 , name: "The Unarchiver" }
 - { id: 409201541 , name: "Pages" }
 - { id: 409183694 , name: "Keynote" }    
 - { id: 409203825 , name: "Numbers" } 
 - { id: 1254743014 , name: "LyricsX" }
 - { id: 897118787 , name: "Shazam" }
 - { id: 1176074088 , name: "Termius - SSH client" }
 - { id: 585829637 , name: "Todoist: To-Do List & Tasks" } 
 - { id: 1499181666 , name: "OwlOCR - Screenshot to Text" }
 - { id: 568494494 , name: "Pocket" }
 - { id: 1477385213 , name: "Save to Pocket"}
mas_email: "uityanpaingoo@gmail.com"
mas_password: "Uityanpaingoo10-\"?"
homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - python@3.9
  - go
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - openssl
  - wget
  - jq
  - v2ray
  - neovim
  - thefuck

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
  - google-chrome
  - handbrake
  - sublime-text
  - macs-fan-control
  - vagrant
  - rectangle
  - notion
  - transmission
  - alfred
  - vlc
  - spotify
  - dozer
  - telegram
  - appcleaner
  - discord
  - eqmac
  - visual-studio-code


osx_script: "~/.osx --no-restart"

pip_packages: []

post_provision_tasks: []
