---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_osx: false

configure_dock: false
dockitems_remove: []
dockitems_persist: []

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/ypo777/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Developer/dotfiles
dotfiles_files:
  - .gitignore
  - .gitconfig
dotfiles_folder:
  - starship.toml
homebrew_installed_packages:
  - git

homebrew_taps:
  - homebrew/core
  - homebrew/cask

mas_installed_apps: []
mas_email: ""
mas_password: ""


post_provision_tasks: []
