---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_osx: false

configure_dock: false
dockitems_remove: []
dockitems_persist: []

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  - git

homebrew_taps:
  - homebrew/core
  - homebrew/cask

mas_installed_apps: []
mas_email: ""
mas_password: ""


post_provision_tasks: []
