---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_osx: true

configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Safari
  - Maps
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Music
  - Podcasts
  - News
  - 'App Store'

dockitems_persist:
  - name: "Firefox"
    path: "/Applications/Firefox.app"
    pos: 2
  - name: "Alacritty"
    path: "/Applications/Alacritty.app"
    pos: 5

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/ypo777/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Developer/dotfiles
dotfiles_files:
  - .gitignore
  - .gitconfig
dotfiles_folder:
  - starship.toml
homebrew_installed_packages:
  - git

homebrew_taps:
  - homebrew/core
  - homebrew/cask

mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.macos --no-restart"


composer_packages: []

gem_packages: []

npm_packages: []

pip_packages:
  - name: scikit-learn
    state: latest
  - name: pandas
    state: latest

post_provision_tasks: []
