---
- hosts: all

  vars_files:
    - default.config.yml

  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: Ensure ~/.config directory exists
      file:
        path: "{{ lookup('env', 'HOME') }}/.config"
        state: directory
        mode: '0755'
      tags: ['always']

  tasks:
    - import_role:
        name: elliotweiser.osx-command-line-tools

    - import_role:
        name: geerlingguy.mac.homebrew
      tags: ['homebrew']

    - import_role:
        name: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

    - import_tasks: tasks/fish-setup.yml
      tags: ['fish']

    - import_role:
        name: geerlingguy.mac.mas
      when: mas_installed_apps
      tags: ['mas']

    - import_role:
        name: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/macos.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']

  handlers:
    - name: Restart Finder
      become: false
      command: killall Finder
      failed_when: false
      changed_when: false

    - name: Restart Dock
      become: false
      command: killall Dock
      failed_when: false
      changed_when: false

    - name: Restart SystemUIServer
      become: false
      command: killall SystemUIServer
      failed_when: false
      changed_when: false

    - name: Restart WindowManager
      become: false
      command: killall WindowManager
      failed_when: false
      changed_when: false
