---
dotfiles_repo: "https://github.com/ypo777/dotfiles.git"
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: "~/dotfiles"

dotfiles_home: "~"
dotfiles_files:
  - .gitignore
  - .gitconfig
